# Generated by Django 3.0.4 on 2020-04-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='make_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
