# Generated by Django 3.0.4 on 2020-04-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMeApp', '0002_auto_20200425_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar.jpeg', upload_to='avatars'),
        ),
    ]
