# Generated by Django 3.0.4 on 2020-04-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMeApp', '0003_auto_20200427_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.jpeg', upload_to='avatars'),
        ),
    ]
