# Generated by Django 3.0.4 on 2020-05-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMeApp', '0005_auto_20200515_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_count',
            field=models.IntegerField(default=0, verbose_name='Количество ответов'),
        ),
    ]
