# Generated by Django 3.0.4 on 2020-05-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMeApp', '0006_question_answers_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
        migrations.AddField(
            model_name='answer',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AddField(
            model_name='question',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AddField(
            model_name='question',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
    ]
