# Generated by Django 3.0.4 on 2020-05-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMeApp', '0007_auto_20200520_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='dislikes_count',
            field=models.IntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dislikes_count',
            field=models.IntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
    ]
