# Generated by Django 3.0.4 on 2020-05-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMeApp', '0008_auto_20200520_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers_count',
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Название тэга'),
        ),
    ]
