# Generated by Django 3.0.4 on 2020-06-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMeApp', '0009_auto_20200530_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes_count',
        ),
        migrations.AlterField(
            model_name='question',
            name='make_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Рейтинг'),
        ),
    ]
