# Generated by Django 3.0.4 on 2020-06-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMeApp', '0011_auto_20200602_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='questions_count',
            field=models.IntegerField(default=0),
        ),
    ]
