# Generated by Django 3.0.4 on 2020-06-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AskMeApp', '0013_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='questions_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
